"""Add user_id to playlists and fix playlist model

Revision ID: 91d94beea65e
Revises: 6b1159946e77
Create Date: 2026-04-30 22:15:21.491481

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91d94beea65e'
down_revision: Union[str, None] = '6b1159946e77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('playlists', sa.Column('user_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'playlists', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'playlists', type_='foreignkey')
    op.drop_column('playlists', 'user_id')
    # ### end Alembic commands ###
